name: scoper
description: A minimal state management solution for Flutter.
version: 0.0.1+2
homepage: https://github.com/kohjakob/scoper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
